version: '3.8'

services:
  # API Gateway service
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=FireworksDB
      - RABBITMQ_HOST=rabbitmq
      - BB_CONFIG_PATH=API/resources/app_secrets.json
    volumes:
      - ./API/resources:/app/API/resources
    depends_on:
      - db
      - rabbitmq
    networks:
      - hagley-network

  # Worker service for asynchronous processing of sync tasks
  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=FireworksDB
      - RABBITMQ_HOST=rabbitmq
      - BB_CONFIG_PATH=API/resources/app_secrets.json
    volumes:
      - ./API/resources:/app/API/resources
    depends_on:
      - db
      - rabbitmq
    networks:
      - hagley-network
    deploy:
      replicas: 2  # Deploy multiple workers for scalability

  # Message broker for event-driven architecture
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI port
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - hagley-network

  # MySQL database
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=FireworksDB
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/DB_Fireworks.sql:/docker-entrypoint-initdb.d/DB_Fireworks.sql
    networks:
      - hagley-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  rabbitmq_data:
  mysql_data:

networks:
  hagley-network:
    driver: bridge